# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  ruby: circleci/ruby@1.7.1
  node: circleci/node@5.0.2
  browser-tools: circleci/browser-tools@1.3.0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    docker:
      - image: cimg/ruby:2.6.10-node
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
    steps:
      - checkout
      - ruby/install-deps:
          bundler-version: 2.1.4
      - node/install-packages: 
          pkg-manager: yarn

  test:
    docker:
      - image: cimg/ruby:2.6.10-node
      - image: cimg/postgres:14.2
        environment:
            POSTGRES_USER: circleci
            POSTGRES_DB: myrecipe_test
            POSTGRES_HOST_AUTH_METHOD: trust # パスワードなし
    environment:
        BUNDLE_JOBS: "3"
        BUNDLE_RETRY: "3"
        PGHOST: 127.0.0.1
        PGUSER: circleci
        PGPASSWORD: ""
        TZ: "/usr/share/zoneinfo/Asia/Tokyo"
        RAILS_ENV: test

    steps:
      - checkout
      - ruby/install-deps:
          bundler-version: 2.1.4
      - node/install-packages: 
          pkg-manager: yarn
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: DB Initializing
          command: |
            dockerize -wait tcp://localhost:5432 -timeout 1m
            bundle exec rake db:schema:load
      - run:
          name: rspec
          command: |
            bundle exec rspec 
      - store_test_results:
          path: test_results

workflows:
  version: 2.1
  build_and_test:
    jobs:
        - build
        - test:
            requires:
              - build